### PR TITLE
fix double building  in dev mode

### PR DESCRIPTION
**Pull request by yurks**
And deps versions could be bumped now)

### CODE REVIEW

**Comment by AngelMunoz** [comment]
@yurks mind to bump and update readme (plus attributing you the change) in a separate pr?

**Comment by AngelMunoz** [comment]
@yurks thank you by the way! I was kind of bussy earlier, but I do appreciate it

**Comment by yurks** [comment]
> @yurks mind to bump and update readme (plus attributing you the change) in a separate pr?

I thought you would do it as owner ;)


> @yurks thank you by the way! I was kind of bussy earlier, but I do appreciate it

np, thank you too for this template

**Comment by AngelMunoz** [comment]
>I thought you would do it as owner ;)

Yeah I can do it, let me find some time on the weekend and I'll try to bump stuff up

**Pull request merged**
